#Tag the instance
      - name: Add tag to Instance(s)
        ec2_tag:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          resource: "{{ item.id }}"
          region: "{{ region }}"
          state: "present"
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Type: tomcatserver
