      - name: Create a security group
        ec2_group:
          name: "{{ security_group }}"
          description: The tomcat security group
          region: "{{ region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          rules:
            # Only allow from NAT instance
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 10.10.0.0/24
              #tomcat to the world
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
