---
  - name: load security file
    include_vars: "aws_keys.yml"
    tags:
      - always

  - name: create security group
    include_tasks: create_sec_group.yml
    vars:

      security_group: tomcatservers_sg

    tags:
      - always

  - name: launch ec2 instance
    include_tasks: launch_ec2.yml
    tags:
      - always

  - name: create security group
    include_tasks: create_sec_group.yml
    tags:
      - always

  - name: add host entry to hosts file
    include_tasks: add_host_entry.yml
    tags:
      - always

  - name: verify state of ec2 instance
    include_tasks: verify_ec2.yml
    tags:
      - always
