#Before starting to communicate, need to ensure that the creation process is complete
#SSH daemon is ready to receive connections

      - name: Wait for SSH to come up
        wait_for:
          timeout: 60
          host: "{{ item.public_ip }}"
          port: 22
          state: started
        with_items: "{{ ec2.instances }}"
      - meta: refresh_inventory  
